language: node_js
node_js:
  - '6'
  - '8'
  - '10'
  - 'node'
env:
  - NODE_ENV=TEST

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  yarn: true
  directories:
    - 'node_modules'
script:
  - yarn install
  # - yarn coveralls
